### PR TITLE
MAINT-1968 Fix code quality warnings and recommendation from LGTM report.

### PR DESCRIPTION
**Pull request by kaicode**
@CoderMChu I checked the LGTM report and found a couple of issues.
This PR fixes the 2 warnings and 1 recommendation but I'm not sure how best to tackle the 1 error that was raised. Let's talk further.

### CODE REVIEW

**Review by CoderMChu — APPROVED** [review]
@kaicode It looks good. Thanks.

**Comment by CoderMChu** [comment]
@kaicode  We don't seem to use the values in "internalIdsToHide" after being collected. We could remove it to avoid the error about "The contents of this container are never accessed." Maybe this was added when we were debugging locally.

**Comment by CoderMChu** [comment]
@kaicode After checking the commit history, we used to update the branch with this. However the internal id is added via the commit object now. https://github.com/IHTSDO/snowstorm/blob/develop/src/main/java/org/snomed/snowstorm/core/data/services/BranchMergeService.java#L494

**Comment by CoderMChu** [comment]
@kaicode Thanks. I will fix the remaining error.

**Comment by kaicode** [comment]
Thanks @CoderMChu !

**Comment by kaicode** [comment]
@CoderMChu you are right that the internalId is being added to the commit, maybe they are only added to the `internalIdsToHide` collection for debugging or logging purposes. That doesn't look like it's needed 👍

**Pull request merged**
