### PR TITLE
-> SwaggerBootstrapUi

### PR DESCRIPTION
**Pull request by lihaiming**
1. swagger -> SwaggerBootstrapUi which is more powerful
2. server.port=8421
3. <skipTests>true</skipTests> to skip unit test by default. one can still change it to false to run through the tests

### CODE REVIEW

**Comment by lihaiming** [comment]
server IP address should be changed to [localhost] to be normalized.

**Comment by lihaiming** [comment]
Hi There,

You may have a try and feel the new swaggerUi at my local deployment <http://119.3.193.23:8421/doc.html?showMenuApi=1&showDes=1&cache=1&cacheApi=1&filterApi=1&filterApiType=POST&lang=en>.

Thanks.

**Comment by kaicode** [comment]
Hi @lihaiming. Thank you for your suggestion and for providing a test deployment to try out these changes.

While I like the idea of the side navigation in SwaggerBootstrapUi I'm finding the rest of the interface quite busy and not really an improvement on what we already have. There are some other features in there too like setting custom headers etc but I'm not sure they will be of any use to our users for exploring the API. 

I would like to incorporate more documentation into the Swagger interface at some point but at the moment I think it's good to keep it as simple as possible. We are also experimenting with Postman which is very popular and has some of the features that SwaggerBootstrapUi seems to add. We also like apiary.io which has side navigation on the left, documentation in the middle and try-it-out functionality on the right.

Thanks for contributing back something you have found useful but I don't think this is a good fit for most users who are looking for a minimal clean interface for exploring this API.

Kind regards,
Kai

**Comment by lihaiming** [comment]
Hi Kai,

Appreciate your insightful response. Yes please just ignore my small suggestion.

I am new to SNOMED-CT tool chain.
My team and I will keep learning and exploring, anyway!

Regards,
Haiming

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Kai Kewley <notifications@github.com>
发送时间: Tuesday, July 2, 2019 11:47:39 PM
收件人: IHTSDO/snowstorm
抄送: haimingli; Mention
主题: Re: [IHTSDO/snowstorm] -> SwaggerBootstrapUi (#54)


Hi @lihaiming<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flihaiming&data=02%7C01%7C%7Ca1ef10bde53043582eb408d6ff049d48%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636976792610453777&sdata=ezi8smvA%2BpiAmv%2BhAQUcYN5UCigl2qma9xTrihqHBfI%3D&reserved=0>. Thank you for your suggestion and for providing a test deployment to try out these changes.

While I like the idea of the side navigation in SwaggerBootstrapUi I'm finding the rest of the interface quite busy and not really an improvement on what we already have. There are some other features in there too like setting custom headers etc but I'm not sure they will be of any use to our users for exploring the API.

I would like to incorporate more documentation into the Swagger interface at some point but at the moment I think it's good to keep it as simple as possible. We are also experimenting with Postman which is very popular and has some of the features that SwaggerBootstrapUi seems to add. We also like apiary.io which has side navigation on the left, documentation in the middle and try-it-out functionality on the right.

Thanks for contributing back something you have found useful but I don't think this is a good fit for most users who are looking for a minimal clean interface for exploring this API.

Kind regards,
Kai

―

**Comment by kaicode** [comment]
Thanks Haiming. Feel free to drop me an email if you have any questions, big or small! kke@snomed.org
Kai

**Pull request closed without merging**
