### PR TITLE
spring.config.additional-location

### PR DESCRIPTION
**Pull request by danka74**
Replace --spring.config.location with non-replacing --spring.config.additional-location.
https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.config.additional-location
Addresses #366

### CODE REVIEW

**Comment by kaicode** [comment]
We are dropping the use of `spring.config.location` in favour of using the root context (`/`) and allowing Nginx to specify the context using `proxy_set_header X-Forwarded-Prefix /snowstorm/snomed-ct;`
That is already in the development environment and should come into effect in the next Snowstorm release.
Will that make this PR redundant @danka74 ?

**Comment by danka74** [comment]
Sorry, X-Forwarded-Path is for the server.servlet.contextPath property, isn't it? There would still be configuration going on?

**Comment by danka74** [comment]
So, I guess the PR is not redundant, with the contextPart as the exception. It's about the location of the configuration .properties file and that local properties should complement and not replace default. Or did I misunderstand?

**Comment by kaicode** [comment]
Yes, you are right. Sorry for my first comment, that was misleading.

**Review by kaicode — APPROVED** [review]
A valuable documentation change. Looks good.

**Comment by kaicode** [comment]
Thanks @danka74 !

**Pull request merged**
