### PR TITLE
MAINT-1862 - Added searchAfter paging to SDottedExpressionConstraint

### PR DESCRIPTION
**Pull request by astro-snail**

### CODE REVIEW

**Review by CoderMChu — COMMENTED** [review]
@astro-snail The fix looks good to me. It would be great if you can add a test case. Thanks.

**Comment by astro-snail** [comment]
@CoderMChu Added a test case for pagination with searchAfter

**Review by CoderMChu — COMMENTED** [review]
@astro-snail  You could either add searchAfter page request assertions in existing test method or extract data set up to a private method to avoid copy and paste. Apart from that it looks good. Thanks.

**Comment by astro-snail** [comment]
> 

Will do that. Thanks. Just was not sure if 2 methods using the same code already justify a private setup method.

**Review by CoderMChu — APPROVED** [review]
@astro-snail Great it looks good. Thanks.

**Pull request merged**
