### PR TITLE
Support for multiple conceptIds in input params of REST findDescriptions operation

### PR DESCRIPTION
**Pull request by jbarcas**

### CODE REVIEW

**Comment by kaicode** [comment]
Hi @jbarcas, could you rebase this pull request against the upstream develop branch please?

**Comment by jbarcas** [comment]
done!

**Comment by kaicode** [comment]
I'm so sorry @jbarcas, thank you for rebasing your pull request. We are currently testing version 5.x in our UAT environment and just had to make another release and force push to develop. Could you rebase again please? I'll jump onto reviewing this as quick as possible so you shouldn't need to rebase again.

**Comment by kaicode** [comment]
I reviewed the commit against #142 and it looks good to me. I'll merge once rebased (again - sorry).

**Comment by jbarcas** [comment]
yup! no problem, done! ;-)

**Review by kaicode — APPROVED** [review]
Looks good to me. Thank you!

**Pull request merged**
