### PR TITLE
RT2-130

### PR DESCRIPTION
**Pull request by RichardAWood**
Modification to findConceptChildren.  If a refset id is included, the output indicates whether any of the returned children have descendants that are members of the specified refset.  Required for RT2.

### CODE REVIEW

**Comment by RichardAWood** [comment]
Ah - I see you requested changes to the previous PR 292.  I'll make update things here and close out 292.

**Review by kaicode — CHANGES_REQUESTED** [review]
Yes, it looks like all my comments from the previous PR for this ticket apply here too.

**Comment by RichardAWood** [comment]
Comments about changes made on PR 292. Pushing changes now.

**Review by kaicode — APPROVED** [review]
Looks good to me!

**Pull request merged**
