### PR TITLE
MAINT-1027 Fetch first 10K results for branch children API endpoint and Paging.

### PR DESCRIPTION
**Pull request by kparmar1**

### CODE REVIEW

**Comment by kparmar1** [comment]
Comment by @danka74 

FWIW, I have built some code around the fact that snowstorm paginates results using rxjs observables. It works fine but I see that performance is increased significantly by lowering page size to e.g. 1k compared to 10k. When doing large-ish tasks as translating every defined medicinal product (20k concepts) it is the difference between a 30 min job and not finishing over night.

**Comment by kparmar1** [comment]
@kaicode Changes made to the names. The regex should be good to match as it already accounts for everything after the '/' but not a '/'.

The tests after the change were fine.

**Comment by kaicode** [comment]
Ah, I see now. The regex could be simplified to `[^/]*`, I think that's what confused me. Looks good. Will merge.

**Comment by kparmar1** [comment]
@kaicode Thanks.

**Pull request merged**
